# 
    Share files on any machine, running any operating with users on the Internet
    Allow your clients, friends and business partners to upload large files to your network
    An ideal solution for replacing FTP servers
    Create public links for users to upload or download files to your machine right from their email
    100% web-based - all you need is a browser on the client's end.
    Secure and very easy to install
